spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/telemetry-db-server
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        generate_statistics: true
  kafka:
    bootstrap-servers: localhost:9092

security:
  jwt:
    secret-key: DXG2B1EsyvPChpB2Y7zBTQMKAz1u+fOrIAtdkTe8QIn6oFvOIYtOurwQwE3yd/qHiMROOxqT6Eue5RKeRHHySQ==
    expiration-hours: 12

logging:
  level:
    root: INFO
   # org.acme.telemetry_service: DEBUG
    # org.hibernate.SQL: DEBUG
    # com.zaxxer.hikari.HikariConfig: INFO
    #org.springframework.orm.jpa: INFO
    #org.springframework.jdbc.core: DEBUG
    # org.springframework.transaction: INFO